import test from 'node:test';
import assert from 'node:assert/strict';
let counter=0;
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};};
async function fresh(){return import('../src/api.js?verification='+counter++);}
function browser(){globalThis.localStorage=memory();globalThis.sessionStorage=memory();globalThis.location={hash:'',pathname:'/howdybiz/',search:'',origin:'https://owner.github.io'};globalThis.history={replaceState(_state,_title,url){assert.equal(url.includes('access_token'),false);assert.equal(url,'/howdybiz/');}};globalThis.fetch=async(url,options)=>url==='./config.json'?{ok:true,json:async()=>({supabaseUrl:'https://verification.supabase.co',publishableKey:'sb_publishable_verification'})}:{ok:true,json:async()=>{if(url.endsWith('/auth/v1/user')){assert.equal(options.headers.Authorization,'Bearer synthetic-owner-session');return {id:'synthetic-owner',email:'owner@example.com'};}return {};}};}
test('email-link session survives opening another dashboard tab and sign-out clears both stores',async()=>{browser();location.hash='#access_token=synthetic-owner-session&refresh_token=synthetic-refresh&expires_in=3600';const first=await fresh();await first.initialize();assert.ok(localStorage.getItem('howdybiz.auth'));location.hash='';globalThis.sessionStorage=memory();const second=await fresh();await second.initialize();assert.equal((await second.user()).email,'owner@example.com');await second.logout();assert.equal(localStorage.getItem('howdybiz.auth'),null);assert.equal(sessionStorage.getItem('howdybiz.auth'),null);assert.equal(await second.user(),null);});
test('existing tab-scoped owner sessions migrate without another sign-in',async()=>{browser();sessionStorage.setItem('howdybiz.auth',JSON.stringify({access_token:'synthetic-owner-session',refresh_token:'synthetic-refresh',expires_at:Date.now()+3600000}));const api=await fresh();await api.initialize();assert.equal((await api.user()).id,'synthetic-owner');assert.ok(localStorage.getItem('howdybiz.auth'));assert.equal(sessionStorage.getItem('howdybiz.auth'),null);});

test('an already open dashboard restores a new-tab sign-in and observes cross-tab sign-out',async()=>{browser();const api=await fresh();await api.initialize();assert.equal(await api.user(),null);localStorage.setItem('howdybiz.auth',JSON.stringify({access_token:'synthetic-owner-session',refresh_token:'synthetic-refresh',expires_at:Date.now()+3600000}));assert.equal(api.syncSession(),true);assert.equal((await api.user()).email,'owner@example.com');assert.equal(api.syncSession(),false);localStorage.removeItem('howdybiz.auth');assert.equal(api.syncSession(),true);assert.equal(await api.user(),null);});
test('invalid stored sessions do not crash startup or masquerade as authenticated sessions',async()=>{browser();localStorage.setItem('howdybiz.auth','invalid-json');const api=await fresh();await api.initialize();assert.equal(await api.user(),null);localStorage.setItem('howdybiz.auth','{"email":"owner@example.com"}');assert.equal(api.syncSession(),false);assert.equal(await api.user(),null);});
