import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.HOWDY_PGLITE_MODULE||'@electric-sql/pglite');
const owner='00000000-0000-4000-8000-000000000001';
async function setup(){
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
 await db.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/connector-queue.sql',import.meta.url),'utf8'));
 await db.query('insert into auth.users(id) values($1)',[owner]);
 await db.query('insert into public.workspace_settings(user_id) values($1)',[owner]);
 await db.query("insert into private.connector_config(id,owner_id,owner_email,enabled) values(1,$1,'owner@example.com',true)",[owner]);
 await db.query("insert into private.gmail_accounts(user_id,email,verified,refresh_token,transport) values($1,'owner@example.com',true,'connector-managed','connector')",[owner]);
 const b=(await db.query("insert into public.businesses(user_id,place_id,mode,data) values($1,'web:verified','demo',$2) returning id",[owner,{name:'Verified',email:'business@example.com',phone:'5125550123',sample:false,stage:'New'}])).rows[0].id;
 return {db,b};
}
async function preview(db,b,patch={}){const envelope={mode:'demo',revision:0,to:'owner@example.com',subject:'TEST',body:'DEMO TEST\nVerified body',cc:[],bcc:[],...patch};return (await db.query("select public.howdy_private('ticket','put',$1,$2) t",[owner,{business_id:b,envelope,mode:'demo',revision:0}])).rows[0].t;}
async function submit(db,b){const t=await preview(db,b);const j=(await db.query('select public.howdy_connector_submit($1,$2,0) j',[owner,t.id])).rows[0].j;return {t,j};}
test('connector RPCs and private queue are inaccessible to browser roles',async()=>{const {db}=await setup();try{await db.exec('set role authenticated');await assert.rejects(db.query('select public.howdy_connector_tick()'),/permission denied/);await assert.rejects(db.query('select * from private.connector_jobs'),/permission denied/);}finally{await db.close();}});
test('preview does not enqueue; explicit submit freezes mail and blocks duplicates',async()=>{const {db,b}=await setup();try{const t=await preview(db,b);assert.equal((await db.query('select * from private.connector_jobs')).rows.length,0);const j=(await db.query('select public.howdy_connector_submit($1,$2,0) j',[owner,t.id])).rows[0].j;assert.equal(j.status,'queued');await assert.rejects(db.query('select public.howdy_connector_submit($1,$2,0)',[owner,t.id]),/Duplicate/);const duplicate=await preview(db,b);await assert.rejects(db.query('select public.howdy_connector_submit($1,$2,0)',[owner,duplicate.id]),/Duplicate/);const c=(await db.query('select public.howdy_connector_claim($1,$2) j',[j.id,'owner@example.com'])).rows[0].j;assert.equal(c.envelope.to,'owner@example.com');assert.equal(c.envelope.subject,'TEST');assert.deepEqual(c.envelope.cc,[]);assert.equal((await db.query('select public.howdy_connector_claim($1,$2) j',[j.id,'owner@example.com'])).rows[0].j,null);}finally{await db.close();}});
test('worker rejects tampered demo CC/BCC and wrong connected identity',async()=>{for(const attack of ['cc','identity']){const {db,b}=await setup();try{const {t,j}=await submit(db,b);if(attack==='cc')await db.query("update private.mail_tickets set envelope=jsonb_set(envelope,'{cc}','[\"attacker@example.com\"]') where id=$1",[t.id]);const c=(await db.query('select public.howdy_connector_claim($1,$2) j',[j.id,attack==='identity'?'other@example.com':'owner@example.com'])).rows[0].j;assert.equal(c,null);assert.equal((await db.query('select status from private.connector_jobs where id=$1',[j.id])).rows[0].status,'failed');}finally{await db.close();}}});
test('mode changes cancel waiting emails and expired previews cannot enqueue',async()=>{const {db,b}=await setup();try{const expired=await preview(db,b);await db.query("update private.mail_tickets set expires_at=now()-interval '1 second' where id=$1",[expired.id]);await assert.rejects(db.query('select public.howdy_connector_submit($1,$2,0)',[owner,expired.id]),/expired/);const {j}=await submit(db,b);await db.query("select public.howdy_mode($1,'live',0)",[owner]);assert.equal((await db.query('select status from private.connector_jobs where id=$1',[j.id])).rows[0].status,'cancelled');assert.equal((await db.query('select public.howdy_connector_claim($1,$2) j',[j.id,'owner@example.com'])).rows[0].j,null);}finally{await db.close();}});
test('Do Not Contact changes block queued email before transport',async()=>{const {db,b}=await setup();try{const {j}=await submit(db,b);await db.query("update public.businesses set data=jsonb_set(data,'{stage}','\"Do Not Contact\"') where id=$1",[b]);assert.equal((await db.query('select public.howdy_connector_claim($1,$2) j',[j.id,'owner@example.com'])).rows[0].j,null);}finally{await db.close();}});
test('in-flight sends block mode changes; provider message ID required to claim sent',async()=>{const {db,b}=await setup();try{const {j}=await submit(db,b);await db.query('select public.howdy_connector_claim($1,$2)',[j.id,'owner@example.com']);await assert.rejects(db.query("select public.howdy_mode($1,'live',0)",[owner]),/send is running/);await assert.rejects(db.query("select public.howdy_connector_finish_email($1,'sent',null,null)",[j.id]),/evidence required/);await db.query("select public.howdy_connector_finish_email($1,'sent','verified-gmail-id',null)",[j.id]);assert.equal((await db.query('select status from private.connector_jobs where id=$1',[j.id])).rows[0].status,'completed');assert.equal((await db.query('select mode from public.workspace_settings')).rows[0].mode,'demo');}finally{await db.close();}});
test('public search persists independent contacts, deduplicates and preserves CRM',async()=>{const {db}=await setup();try{const query={keyword:'florist',zones:'78701',radius:''};const create=async()=>(await db.query('select public.howdy_connector_search($1,0,$2) j',[owner,query])).rows[0].j;const j=await create();assert.equal((await create()).id,j.id);await db.query('select public.howdy_connector_claim($1,$2)',[j.id,'owner@example.com']);const data={name:'Public Florist',category:'Florist',address:'123 Example St',zip:'78701',website:'https://public-business.example.com/',contact_source:'https://public-business.example.com/contact',phone:'5125550123',email:'hello@public-business.example.com',rating:5};const ids=(await db.query('select public.howdy_connector_finish_search($1,$2,$3) ids',[j.id,[data],'Partial coverage; 1 verified public contact.'])).rows[0].ids;await db.query('update public.businesses set data=data||$1 where id=$2',[{notes:'Keep note',stage:'Qualified'},ids[0]]);const again=await create();await db.query('select public.howdy_connector_claim($1,$2)',[again.id,'owner@example.com']);await db.query('select public.howdy_connector_finish_search($1,$2,$3)',[again.id,[data],'Partial coverage.']);const b=(await db.query('select data from public.businesses where id=$1',[ids[0]])).rows[0].data;assert.equal(b.notes,'Keep note');assert.equal(b.stage,'Qualified');assert.equal(b.rating,undefined);assert.equal(b.website_status,'Unchecked');assert.equal((await db.query("select count(*) as n from public.businesses where mode='live'")).rows[0].n,0);}finally{await db.close();}});
test('demo clearing cancels searches; no late result can repopulate the workspace',async()=>{const {db}=await setup();try{const j=(await db.query('select public.howdy_connector_search($1,0,$2) j',[owner,{keyword:'florist',zones:'78701'}])).rows[0].j;await db.query('select public.howdy_connector_claim($1,$2)',[j.id,'owner@example.com']);await db.query('select public.howdy_clear_demo($1)',[owner]);await assert.rejects(db.query('select public.howdy_connector_finish_search($1,$2,$3)',[j.id,[],'No results.']),/not running/);assert.equal((await db.query('select * from public.businesses')).rows.length,0);}finally{await db.close();}});
