import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
const {chromium}=await import(process.env.HOWDY_PLAYWRIGHT_MODULE||'playwright');
const root=resolve('dist'),out=resolve('test-results');await mkdir(out,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname.replace(/^\/howdybiz\//,'/');const file=resolve(root,'.'+(p.endsWith('/')?p+'index.html':p));if(!file.startsWith(root+'/'))throw Error('Invalid path');res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.statusCode=404;res.end();}});
await new Promise(resolve=>server.listen(4174,'127.0.0.1',resolve));
const browser=await chromium.launch({...(process.env.HOWDY_CHROMIUM_PATH?{executablePath:process.env.HOWDY_CHROMIUM_PATH}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-proxy-server','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const checks=[],errors=[];const record=name=>{checks.push(name);console.log('PASS '+name);};
try{
  const page=await browser.newPage({viewport:{width:1536,height:1080}});page.on('pageerror',err=>errors.push(err.message));
  await page.goto('http://127.0.0.1:4174/howdybiz/');
  assert.equal(await page.getByRole('switch',{name:'Demo Mode'}).getAttribute('aria-checked'),'true');record('Default demo toggle is visible and ON');
  await page.getByRole('button',{name:'Load sample workspace'}).click();assert.equal(await page.locator('tbody tr').count(),6);record('Six complete-contact samples in results');
  await page.getByRole('button',{name:/Enrichment queue/}).click();assert.match(await page.locator('dialog').innerText(),/Cedar Home Services/);await page.getByRole('button',{name:'Close dialog'}).click();record('Incomplete sample is isolated in enrichment queue');
  await page.locator('#filter-score').selectOption('Potential');assert.equal(await page.locator('tbody tr').count(),3);await page.locator('#filter-score').selectOption('');record('Opportunity filter combines with qualification');
  await page.locator('[name="keyword"]').fill('Florists');await page.locator('[name="zones"]').fill('78701, 78704');await page.getByRole('button',{name:'Toggle light and dark theme'}).click();assert.equal(await page.locator('[name="keyword"]').inputValue(),'Florists');record('Theme change preserves search input');await page.getByRole('button',{name:'Toggle light and dark theme'}).click();
  await page.getByRole('button',{name:'Open Juniper Coffee House',exact:true}).click();await page.locator('[name="notes"]').fill('Owner needs a booking workflow.');await page.locator('[name="stage"]').selectOption('In Progress');await page.getByRole('button',{name:'Save updates',exact:true}).click();
  await page.reload();await page.getByRole('button',{name:'Open Juniper Coffee House',exact:true}).click();assert.equal(await page.locator('[name="notes"]').inputValue(),'Owner needs a booking workflow.');assert.equal(await page.locator('[name="stage"]').inputValue(),'In Progress');record('Demo CRM notes and stage persist across reload within the tab');
  await page.getByRole('button',{name:'Prepare Proposal / Quote',exact:true}).click();await page.locator('[name="scope"]').fill('Build a business website.');await page.locator('[name="deliverables"]').fill('Responsive website and inquiry form.');await page.locator('[name="timeline"]').fill('Two weeks');await page.locator('[name="amount"]').fill('1200');await page.locator('[name="terms"]').fill('50% deposit, balance on completion.');await page.getByRole('button',{name:'Save proposal',exact:true}).click();
  await page.getByRole('button',{name:'Open Juniper Coffee House',exact:true}).click();assert.match(await page.locator('dialog').innerText(),/v1/);record('Proposal created and versioned');
  await page.getByRole('button',{name:'Record payment',exact:true}).click();await page.locator('[name="amount"]').fill('600');await page.locator('[name="reference"]').fill('Deposit record');await page.getByRole('button',{name:'Save payment record',exact:true}).click();record('Manual payment recorded');
  await page.getByRole('button',{name:'Open Juniper Coffee House',exact:true}).click();await page.getByRole('button',{name:/Prepare Email/}).click();await page.locator('[name="body"]').fill('Reviewed test draft.');await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('button',{name:'Review actual send',exact:false}).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Sign in'));assert.equal(await page.locator('#send-email').count(),0);record('Unconfigured backend blocks email send; draft does not send');await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('button',{name:'Load sample workspace'}).click();assert.equal(await page.locator('tbody tr').count(),6);await page.getByRole('button',{name:'Open Juniper Coffee House',exact:true}).click();assert.equal(await page.locator('[name="notes"]').inputValue(),'Owner needs a booking workflow.');await page.getByRole('button',{name:'Close dialog'}).click();record('Reloading samples deduplicates and preserves CRM');
  await page.getByRole('switch',{name:'Demo Mode'}).click();assert.equal(await page.getByRole('switch',{name:'Demo Mode'}).getAttribute('aria-checked'),'true');record('Unconfigured app cannot silently enter Live mode');
  await page.locator('#toast').evaluate(el=>el.className='');await page.screenshot({path:out+'/desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Open Juniper Coffee House',exact:true}).click();await page.screenshot({path:out+'/detail.png',fullPage:true});await page.getByRole('button',{name:'Close dialog'}).click();
  for(const width of [390,768]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);}
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/mobile.png',fullPage:true});record('390px and 768px layouts have no page overflow');
  await page.getByRole('button',{name:'Clear demo data',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();assert.equal(await page.locator('tbody tr').count(),0);record('Demo clear removes temporary records');
  const portable=await browser.newPage();portable.on('pageerror',err=>errors.push(err.message));await portable.goto('file://'+resolve('HowdyBiz-Preview.html'));await portable.getByRole('button',{name:'Load sample workspace'}).waitFor();assert.equal(await portable.locator('tbody tr').count(),6);record('Self-contained HTML preview opens with fictional samples');
  assert.deepEqual(errors,[]);record('No uncaught JavaScript errors');
  await writeFile(out+'/ui-check.json',JSON.stringify({checks,errors},null,2));
}finally{await browser.close();server.close();}
